USE school;
CREATE OR REPLACE VIEW AllDBN AS SELECT DBN, School FROM EMS_2013_All UNION SELECT DBN, School FROM EMS_2012_All UNION SELECT DBN, School FROM EMS_2011_All UNION SELECT DBN, School FROM EMS_2010_All UNION SELECT DBN, School FROM EMS_2009_All UNION SELECT DBN, School FROM EMS_2008_All UNION SELECT DBN, School FROM EMS_2007_All;
SELECT COUNT(DISTINCT DBN) FROM AllDBN;